### PR TITLE
Pom cleanup

### PR DESCRIPTION
**Pull request by rsertelon**
Hi @jsevellec ,

I've cleaned up the POMs of the projects, based upon my own maven experience. Most of this pull request consists in removing uneeded statements, and factorizing a bit more in the parent.

### CODE REVIEW

**Comment by Augi** [comment]
Hi @rsertelon , would you have time to resolve conflicts of this MR? Most of these conflicts are probably caused by my #134 #139 Sorry for that :(

**Comment by rsertelon** [comment]
I can try to. Do you take the lead on this project?

**Comment by Augi** [comment]
No, I just want to get a new release with my changes :-)

**Comment by jsevellec** [comment]
i would say that it's quite an old PR which is not needed for the next release. I'm just moving from milestone to milestone PR/issue that are not integrated/solved.

**Comment by rsertelon** [comment]
I think you can just close it if you want ;) It's purely cosmetics and won't add much to the project after all ;)

**Comment by jsevellec** [comment]
ok

**Pull request closed without merging**
