### PR TITLE
Fix failing tests after update to Cassandra 2.2

### PR DESCRIPTION
**Pull request by Augi**
It's fix of two tests, related to PR#124 https://github.com/jsevellec/cassandra-unit/pull/134

### CODE REVIEW

**Comment by jsevellec** [comment]
hum thantls but it's a bit more than that, there ares tests also failing in the cassandra-unit-spring module.

I'll revert the PR for me moment.

**Comment by Augi** [comment]
Hi, sorry for the late response.

I resolved all the issues with failing tests in cassandra-unit-spring and also merged current master to my repository so it can be easily merged. 

Please note that this MR also includes #134 (update to Cassandra 2.2) that was merged and immediately reverted.

**Comment by jsevellec** [comment]
So cool! I'll have a look asap

**Comment by jsevellec** [comment]
Hi @Augi, really thanks for the contribution. It looks good!

**Comment by amichair** [comment]
When will a release be made that works with Cassandra 2.2.x?

**Comment by jsevellec** [comment]
the release is planned for this week

**Pull request merged**
