### PR TITLE
Multi file datasets

### PR DESCRIPTION
**Pull request by themillhousegroup**
I'm enjoying using CassandraUnit but have found that working with just one file to contain a DataSet is a bit painful - especially if I end up having to copy-paste sections of my data into other files. 

I've written a new `DataSet` implementation called `MultiSourceDataSet` that has two static constructor methods:
```
    public static MultiSourceDataSet fromClassPath(String... classpathFileNames)
    public static MultiSourceDataSet fromFiles(String... fileNames)
```

This allows a full `DataSet` to be created by "merging together" the column families found in each file. The only rules are:
  - Each column family must belong to one keyspace
  - Column families cannot be defined multiple times

I've written tests for all the combinations of success/failure I can think of - hope you like it!

### CODE REVIEW

**Comment by jsevellec** [comment]
hi @themillhousegroup,

thanks for this cool contribution!

**Comment by mcory** [comment]
Any possibility for this to support CQL DataSets? (I haven't found any way to load multiple CQL files into a rule yet....)

**Comment by jsevellec** [comment]
@mcory it's a good idea. Feel free to aise an issue about that

**Comment by jsevellec** [comment]
actually it's possible using the sprint part but not directly https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit-spring/src/test/java/org/cassandraunit/spring/CassandraStartAndLoadWithCQLsDatasetAnnotationTest.java

**Pull request merged**
