### PR TITLE
Upgrade to Cassandra 3.9 and Datastax driver 3.1.1

### PR DESCRIPTION
**Pull request by tandrup**

### CODE REVIEW

**Comment by kubum** [comment]
Does anybody have any idea why it is not merged yet? :)

**Comment by jsevellec** [comment]
no reason, just time ;-). Sorry for that

**Comment by kubum** [comment]
Thanks a lot @jsevellec! Just curious how do you maintain the versioning? I see you added 3.0.0.1, but I also see 3.0.0.1 in MavenCentral dated Mar 18, 2016 or am I looking to the wrong place?

**Comment by jsevellec** [comment]
Hum good point. 

I had an issue during the release of the 3.0.0.1 and i forgot to update the current dev snapshot version. Also I'm trying to follow the cassandra java driver

**Pull request merged**
