### PR TITLE
Upgrade to cassandra 2.1.8

### PR DESCRIPTION
**Pull request by chbatey**
Would it be possible to merge this and do a release? There is a bug with static columns in earlier versions.

### CODE REVIEW

**Comment by jsevellec** [comment]
I'm currently working to try to make it work using cassandra 2.2

**Comment by chbatey** [comment]
Any chance of a higher 2.1 release before going to 2.2? The highest released is 2.1.3 which is quite buggy and there are probably a lot of c* users sticking with 2.1 branch for some time as I can't see 2.2 being prod ready for ~6 months.

**Comment by jsevellec** [comment]
good point. In this case i will make a release with the 2.1.8 first.

**Comment by chbatey** [comment]
Thanks @jsevellec !

**Comment by jsevellec** [comment]
I'll push a release soon but while waiting for it, here is already a snapshot available I've just published a 2.1.8.1-SNAPSHOT built on the last master containing your merged PR.
(https://oss.sonatype.org/content/repositories/snapshots/)

**Pull request merged**
