### PR TITLE
Changed the version of Cassandra-all to 3.11.3

### LINKED ISSUE #267: Issues when using different logging framework to Logback
When we introduced `cassandra-unit` to write integration tests we get the following error message:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/bob/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.10.0/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/bob/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2018-04-26T13:01:14,186 WARN  main  org.apache.cassandra.config.DatabaseDescriptor - index_interval has been deprecated and should be removed from cassandra.yaml
2018-04-26T13:01:14,192 WARN  main  org.apache.cassandra.config.DatabaseDescriptor - Please rename encryption_options as server_encryption_options in the yaml
java.lang.ClassCastException: org.apache.logging.slf4j.Log4jLogger cannot be cast to ch.qos.logback.classic.Logger
	at org.apache.cassandra.cql3.functions.ThreadAwareSecurityManager.install(ThreadAwareSecurityManager.java:92)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:192)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.lambda$startEmbeddedCassandra$1(EmbeddedCassandraServerHelper.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We use a different logging framework to that used in `cassandra-unit` (i.e. Logback) and don't want to migrate to Logback.

I've had a look at the `github` repository for `cassandra-unit` and have noticed that in `org.apache.cassandra.cql3.functions.ThreadAwareSecurityManager`, Logback is hard codded e.g.
`ch.qos.logback.classic.Logger logbackLogger = (ch.qos.logback.classic.Logger) l;`

Is there a reason for hard coding Logback? Will this be resolved in future releases? Is there a workaround for using alternative logging framework where the above error will not be thrown.

We are using `cassandra-unit-spring` version `3.3.0.2` for our integration tests

### PR DESCRIPTION
**Pull request by Ali-Mahmood**
This was updated to resolve #267.

### CODE REVIEW

**Comment by Ali-Mahmood** [comment]
@jsevellec

**Comment by EduardZaft** [comment]
@jsevellec Hallo, can you please merge this fix and release a new version? Cassandra-all is in version 3.11.4 already available.

**Comment by chris-schwartz** [comment]
@jsevellec Any plans to merge this and include in an upcoming release?  Would help me team out with our migration to Java 11.

**Comment by jsevellec** [comment]
Hi, sorry for the delay.

I've even updated to cassandra 3.11.3.

**Pull request closed without merging**
